### ISSUE TITLE
Can't start yeti service

### ISSUE THREAD

**Issue by azfayel** [yeti-platform/yeti#39] opened 2017-03-30 15:24 UTC
### Description
[Can't start yeti service]

### Environment
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
[How are you expecting the application to behave?]
Start on local port 5000
#### Actual behavior
 File "yeti.py", line 11
    print "[+] Yeti started. Point browser to http://localhost:5000/"

**Comment by TobiasTrabelsi** [comment] 2017-03-30 20:55
try starting it with python2 and not with python3

**Comment by azfayel** [comment] 2017-03-31 15:19
Hello,i did it but i have these error from  std output
mars 31 17:19:10 kali uwsgi[29043]: *** Operational MODE: preforking+threaded ***
mars 31 17:19:11 kali uwsgi[29043]: Traceback (most recent call last):
mars 31 17:19:11 kali uwsgi[29043]:   File "./yeti.py", line 6, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.web import webapp
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/web/__init__.py", line 1, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.web.webapp import webapp
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/web/webapp.py", line 12, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.web.api import api
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/web/api/__init__.py", line 1, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.web.api.api import api
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/web/api/api.py", line 32, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.web.api.analytics import ScheduledAnalytics, OneShotAnalytics
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/web/api/analytics.py", line 10, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.analytics_tasks import schedule
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/analytics_tasks.py", line 9, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from core.config.celeryimports import loaded_modules
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/config/celeryimports.py", line 4, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     loaded_modules = Scheduler.get_entries()
mars 31 17:19:11 kali uwsgi[29043]:   File "./core/scheduling.py", line 88, in get_entries
mars 31 17:19:11 kali uwsgi[29043]:     module = importlib.import_module(name)
mars 31 17:19:11 kali uwsgi[29043]:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
mars 31 17:19:11 kali uwsgi[29043]:     __import__(name)
mars 31 17:19:11 kali uwsgi[29043]:   File "/opt/yeti/plugins/analytics/public/network_whois.py", line 2, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from ipwhois import IPWhois
mars 31 17:19:11 kali uwsgi[29043]:   File "/usr/local/lib/python2.7/dist-packages/ipwhois/__init__.py", line 27, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     from .ipwhois import (IPWhois, IPDefinedError, ASNLookupError,
mars 31 17:19:11 kali uwsgi[29043]:   File "/usr/local/lib/python2.7/dist-packages/ipwhois/ipwhois.py", line 43, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     import dns.resolver
mars 31 17:19:11 kali uwsgi[29043]:   File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
mars 31 17:19:11 kali uwsgi[29043]:     import dns.message
mars 31 17:19:11 kali uwsgi[29043]:   File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
mars 31 17:19:11 kali uwsgi[29043]:     print('id %d' % self.id, file=s)
mars 31 17:19:11 kali uwsgi[29043]:                                  ^
mars 31 17:19:11 kali uwsgi[29043]: SyntaxError: invalid syntax
mars 31 17:19:11 kali uwsgi[29043]: unable to load app 0 (mountpoint='') (callable not found or import error)
mars 31 17:19:11 kali uwsgi[29043]: *** no app loaded. going in full dynamic mode ***
mars 31 17:19:11 kali uwsgi[29043]: *** uWSGI is running in multiple interpreter mode ***
mars 31 17:19:11 kali uwsgi[29043]: spawned uWSGI master process (pid: 29043)
mars 31 17:19:11 kali uwsgi[29043]: spawned uWSGI worker 1 (pid: 29049, cores: 2)
mars 31 17:19:11 kali uwsgi[29043]: spawned uWSGI worker 2 (pid: 29050, cores: 2)
mars 31 17:19:11 kali systemd[1]: Started Yeti UWSGI server.
-- Subject: L'unité (unit) yeti_uwsgi.service a terminé son démarrage
-- Defined-By: systemd
 

    Le Jeudi 30 mars 2017 22h55, TobiasTrabelsi <notifications@github.com> a écrit :
 

 try starting it with python2 and not with python3—

**Comment by tomchop** [comment] 2017-03-31 19:16
So I don't really understand what you're trying to do. First of all, from your initial issue I see that the expected behavior is "Start on local port 5000", and the actual behavior is "[+] Yeti started. Point browser to http://localhost:5000/". So it seems Yeti started correctly on port 5000.

From your second comment, I see that you're trying to use Yeti through uwsgi. This is recommended for production, but for testing purposes or occasional use, the flask webserver is good enough (i.e. the one you invoke when doing `$ ./yeti`. Besides, I would not recommend using Kali Linux for production.

**Comment by tomchop** [comment] 2017-04-07 21:02
Still running into this issue?

**Comment by azfayel** [comment] 2017-04-17 11:38
yes, i still run the issue. I run yeti through commande line  ./yeti and with python 2

Traceback (most recent call last):
  File "./yeti.py", line 6, in <module>
    from core.web import webapp
  File "/opt/yeti/core/web/__init__.py", line 1, in <module>
    from core.web.webapp import webapp
  File "/opt/yeti/core/web/webapp.py", line 12, in <module>
    from core.web.api import api
  File "/opt/yeti/core/web/api/__init__.py", line 1, in <module>
    from core.web.api.api import api
  File "/opt/yeti/core/web/api/api.py", line 32, in <module>
    from core.web.api.analytics import ScheduledAnalytics, OneShotAnalytics
  File "/opt/yeti/core/web/api/analytics.py", line 10, in <module>
    from core.analytics_tasks import schedule
  File "/opt/yeti/core/analytics_tasks.py", line 9, in <module>
    from core.config.celeryimports import loaded_modules
  File "/opt/yeti/core/config/celeryimports.py", line 4, in <module>
    loaded_modules = Scheduler.get_entries()
  File "/opt/yeti/core/scheduling.py", line 88, in get_entries
    module = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/yeti/plugins/analytics/public/network_whois.py", line 2, in <module>
    from ipwhois import IPWhois
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/__init__.py", line 27, in <module>
    from .ipwhois import (IPWhois, IPDefinedError, ASNLookupError,
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/ipwhois.py", line 43, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax

When i ran netstat -anltp | grep 5000 ; no socket on this port.
i'm novice and need help .
Thks.

**Comment by tomchop** [comment] 2017-04-17 13:16
It seems some libraries in `/usr/local/lib/python2.7` are using python3 syntax (`print()`). I'd have to install Kali and play around with it to figure out where the problem is coming from.

**Comment by tomchop** [comment] 2017-10-05 21:58
Closing this since it seems to be related to Kali and how Yeti was installed.

**Closed by tomchop** 2017-10-05 21:58 UTC
Labels: help wanted
