### ISSUE TITLE
Production installation manual is not valid - uwsgi from Ubuntu 16.03 won't work

### ISSUE THREAD

**Issue by rozie** [yeti-platform/yeti#260] opened 2018-05-22 17:19 UTC
### Description
Package uwsgi from Ubuntu repo is advised in production usage, but it is too old and won't work. File yeti_uwsgi.service has -w switch which is absent in this package.

Pip version works, probably it's sufficient to add uwsgi to requirements.txt

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 16.04 LTS

**Comment by tomchop** [comment] 2019-05-26 13:30
Yup, we need to change the documentation to Ubuntu 18.04 LTS and adjust the flags.

**Comment by smclinden** [comment] 2019-09-03 21:28
Has there been any progress on this? It appears that the documentation is not sufficient for either Python 2.7 nor Python 3.6/7 on Ubuntu 18.04. I can run the webserver from Python, but not from uwsgi.

**Comment by doomedraven** [comment] 2019-09-03 21:29
what isn't working for you? details? worked for me just fine on ubuntu 18.04 with python 2.7

**Comment by smclinden** [comment] 2019-09-03 21:41
I get an Internal server error.

There is no logging of any sort. No way to determine what isn't working BUT, it works fine when run as a Python app. All of the other yeti_* services are running, normally. 

yeti_uwsgi.service - Yeti UWSGI server
   Loaded: loaded (/lib/systemd/system/yeti_uwsgi.service; enabled; vendor prese
   Active: active (running) since Tue 2019-09-03 21:08:11 UTC; 30min ago
 Main PID: 11575 (uwsgi)
   Status: "uWSGI is ready"
    Tasks: 9 (limit: 4648)
   Memory: 17.2M
   CGroup: /system.slice/yeti_uwsgi.service
           ├─11575 /usr/bin/uwsgi --plugin python --socket 127.0.0.1:8000 -w yet
           ├─11589 /usr/bin/uwsgi --plugin python --socket 127.0.0.1:8000 -w yet
           ├─11590 /usr/bin/uwsgi --plugin python --socket 127.0.0.1:8000 -w yet
           ├─11591 /usr/bin/uwsgi --plugin python --socket 127.0.0.1:8000 -w yet
           └─11592 /usr/bin/uwsgi --plugin python --socket 127.0.0.1:8000 -w yet

Sep 03 21:08:11 docker uwsgi[11575]: unable to load app 0 (mountpoint='') (calla
Sep 03 21:08:11 docker uwsgi[11575]: *** no app loaded. going in full dynamic mo
Sep 03 21:08:11 docker uwsgi[11575]: *** uWSGI is running in multiple interprete
Sep 03 21:08:11 docker uwsgi[11575]: spawned uWSGI master process (pid: 11575)
Sep 03 21:08:11 docker systemd[1]: Started Yeti UWSGI server.
Sep 03 21:08:11 docker uwsgi[11575]: spawned uWSGI worker 1 (pid: 11589, cores: 
Sep 03 21:08:11 docker uwsgi[11575]: spawned uWSGI worker 2 (pid: 11590, cores: 
Sep 03 21:08:11 docker uwsgi[11575]: spawned uWSGI worker 3 (pid: 11591, cores: 
Sep 03 21:08:11 docker uwsgi[11575]: spawned uWSGI worker 4 (pid: 11592, cores:

**Comment by doomedraven** [comment] 2019-09-03 21:42
nothing in /var/log/uwsgi/?

**Comment by smclinden** [comment] 2019-09-03 21:44
The folder contained one folder, app, and it was empty.

**Comment by fl0wc0ntr0l** [comment] 2020-05-19 05:37
Hi all, 

I have just tested and confirmed on my machine that switching from Ubuntu's port of `uwsgi` (2.0.15) to the `pip` installed version (2.0.18) and then running the yeti_uwsgi.service file exactly as written is the correct way to run the service file. However, the YETI docs as written are never clear about which version from which source needs to be installed. `bootstrap.sh` seems to indicate it is the distro version, which if you ask me is outdated compared to pip. 

I believe @rozie 's solution of adding `uwsgi==2.0.18` to `requirements.txt` should be sufficient to close this issue.

**Comment by fl0wc0ntr0l** [comment] 2020-05-19 06:13
Scratch that - I spoke slightly too soon. There is a difference between how uWSGI and systemd want to handle SIGTERM signals sent to the service. uWSGI appears to do a brutal reload while systemd exits the process. This makes the `yeti_uwsgi.service` file as written hang when stopping or restarting using `systemctl stop|restart yeti_uwsgi`, because uWSGI is apparently winning.

The difference is handily marked by Digital Ocean's guide to setting up uWSGI and nginx: https://www.digitalocean.com/community/tutorials/how-to-set-up-uwsgi-and-nginx-to-serve-python-apps-on-centos-7#configure-a-uwsgi-config-file

Adding the option `--die-on-term` to the end of the argument string allows the service to stop and exit without hanging.

**Comment by tomchop** [comment] 2020-05-19 09:23
Thanks @fl0wc0ntr0l, that's really useful. The documentation is due for a revamp. If you can spot the places where it's ambiguous with respect to the bootstrap scripts, please feel free to file a PR!

Otherwise, I've been considering migrating deployment to Docker. I've done some tests and it makes things infinitely simpler and more reproducible. What do you think? Would a docker production install be a no-go for y'all?

**Closed** 2021-06-23 16:16 UTC
Labels: documentation
