### ISSUE TITLE
Observable.Url does not allow local hostname

### ISSUE THREAD

**Issue by trolldbois** [yeti-platform/yeti#115] opened 2017-07-18 15:46 UTC
### Description
When an observable is in the form http://servername/ (not tld) , Url, and the urlnorm package in particular rejects the Observable.

see https://github.com/yeti-platform/yeti/blob/master/core/observables/url.py#L46
and I'm guessing the Url.regex is also a problem.

### Environment
latest head

### Steps to Reproduce
>>> from core.observables import Url
>>> Url.get_or_create(value='http://servername/')
[..]
  File "core/observables/url.py", line 49, in clean
    raise ObservableValidationError("Invalid URL: {}".format(self.value))
core.errors.ObservableValidationError: Invalid URL: http://servername/

#### Expected behavior
Create Url(<http://servername/>)

#### Actual behavior
Fails in error.

**Comment by gaelmuller** [comment] 2017-08-09 18:54
This is the expected behavior. YETI is validating that URLs are considered valid (they are hosted on a valid domain name).

I must say I am not sure that "local" observables are useful to keep. Any other opinions ? cc @tomchop

**Comment by tomchop** [comment] 2017-10-05 21:24
I would argue that it's dangerous to host non-public URLs or hostnames since their resolution, etc. on the remote Yeti host might not reflect "reality". Also, we depend on the `urlnorm` library to decide if the URL is valid or not (this can also be challenged), so changing this behavior is not trivial.

Unless more people want this feature, I would suggest we close it out.

**Closed by tomchop** 2017-10-05 21:24 UTC
